---
# Run with ansible-playbook prepare_ansible_target.yml -i inventory-playbooks -u ubuntu -k --ask-sudu-pass

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
 
  tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)
    
    - name: Fancy way of doing authoried keys
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
